### ISSUE TITLE
/lint: better example possible

### ISSUE THREAD

**Issue by ceedee666** [gvwilson/sdxpy#101]
IMHO the example in `inheritance_example.py` (included in the text [here](https://github.com/gvwilson/sdxpy/blob/ce377531284949ac11fdcb7bf0bbf60b470959af/en/src/linter/index.md?plain=1#L270)) is not very compelling. For me it is unclear why the classes are called `Parent`, `LeftChild`, .... Also it is not clear why the methods are called `green`, `blue` and so on.

Would it be possible to create a more tangible example? If have no good suggestion. The only thing I could think of were animals.
This would lead to classes like `Bird`, `Fish` etc. and methods like `fly` and `swim`. And of cause this immediately leads to the
problem with Penguins 🐧.

**Comment by gvwilson** [comment]
closed in c537f121
