### ISSUE TITLE
/lint: code to generate table missing

### ISSUE THREAD

**Issue by ceedee666** [gvwilson/sdxpy#102]
The python code to generate the table shown [here](https://github.com/gvwilson/sdxpy/blob/ce377531284949ac11fdcb7bf0bbf60b470959af/en/src/linter/index.md?plain=1#L293) is missing. The file `inheritance.py` contains a [method](https://github.com/gvwilson/sdxpy/blob/ce377531284949ac11fdcb7bf0bbf60b470959af/docs/linter/inheritance.py#L40) to create the table.

**Comment by gvwilson** [comment]
closed in c537f121
