### ISSUE TITLE
/lint: additional information required

### ISSUE THREAD

**Issue by ceedee666** [gvwilson/sdxpy#103]
[Here](https://github.com/gvwilson/sdxpy/blob/ce377531284949ac11fdcb7bf0bbf60b470959af/en/src/linter/index.md?plain=1#L313) the text contains the statement:

> One way around this is to [%g method_injection "inject" %] methods into classes

What ware other approaches? What are the advantages and disadvantages to these approaches? I would suggest mentioning other approach and providing reference to background reading. I would also add a reference to registering handler methods discussed [below](https://github.com/gvwilson/sdxpy/blob/ce377531284949ac11fdcb7bf0bbf60b470959af/en/src/linter/index.md?plain=1#L348).

**Comment by gvwilson** [comment]
closed in c537f121
