### ISSUE TITLE
/interpreter - possibly missing function

### ISSUE THREAD

**Issue by peter0083** [gvwilson/sdxpy#115]
Maybe it's just me reading too quickly through the chapter and the slides. Are we missing a `env_set()` function somewhere? or is `env_set()` deliberately left out to be done in exercise: `2. Look at the documentation for Python's ChainMap class and modify the implementation from the slides to use that to manage environments.`?

https://github.com/gvwilson/sdxpy/blob/a8aa230f7fcbd12b4f97d9525ec3d0f586c43664/docs/interpreter/slides/index.html#L359

**Comment by gvwilson** [comment]
My bad - yes, you’ll need to write env_set but I think the implementation is straightforward given env_get. You can also grab the zip file of all the book’s source code (https://third-bit.com/sdxpy/sdxpy-examples.zip) and look in docs/interpreter/func.py for my version.
