### ISSUE TITLE
Just a minor typo - Javascript object notation isn't really mentioned in chapter 3

### ISSUE THREAD

**Issue by linajandren** [gvwilson/sdxpy#126]
Probably left there by mistake. In the list of terms defined at the top of chapter 3, JavaScript Object Notation is mentioned. I don't see it in the chapter, and I'm guessing it's a leftover from the JavaScript version of the book but you may want to remove it here. Sorry about nitpicking :)

**Comment by gvwilson** [comment]
Nitpicking is very welcome - thank you. The chapter does mention JSON in Section 3.1 when talking about how to parse the files containing programs (which are written as lists), but you're right, one mention of `json.load` probably doesn't merit an entry at the start.

**Comment by linajandren** [comment]
Haha... I just didn't realise JSON and JavaScript Object Notation were the same thing. JSON files are everywhere and I never bothered looking up what it means (and rarely really do anything with them except feed them from one piece of code/software to another). So, depending on who your audience is (I'm possibly not enough programmer and my CS courses are a little bit too long ago) you may want to have a tag like "JavaScript Object Notation (JSON)" instead? :)
