### ISSUE TITLE
/reflect: diagram renders incorrectly

### ISSUE THREAD

**Issue by gvwilson** [gvwilson/sdxpy#158]
![Screenshot 2023-07-12 at 23-42-22 Software Design by Example Reflection](https://github.com/gvwilson/sdxpy/assets/911566/d204ae5f-ab9a-4384-adad-08f94f5dbb6c)

Submitted by @Derek-Jones

**Comment by gvwilson** [comment]
Firefox version 108 on Ubuntu

**Comment by gvwilson** [comment]
Unable to reproduce on Firefox 117 and Ubuntu Focal 20.04.6.

**Comment by Derek-Jones** [comment]
Same incorrect behavior on Firefox 115.0.2 running
Distributor ID:	Linuxmint
Description:	Linux Mint 21.1
Release:	21.1
Codename:	vera

**Comment by gvwilson** [comment]
combined with #157
