### ISSUE TITLE
/parse: diagram renders incorrectly

### ISSUE THREAD

**Issue by gvwilson** [gvwilson/sdxpy#159]
![Screenshot 2023-07-12 at 23-38-25 Software Design by Example Parsing Text](https://github.com/gvwilson/sdxpy/assets/911566/f1d87222-da94-485e-9d66-57f4e2456656)

Submitted by @Derek-Jones

**Comment by gvwilson** [comment]
Firefox version 108 on Ubuntu

**Comment by gvwilson** [comment]
Unable to reproduce on Firefox 117 and Ubuntu Focal 20.04.6.

**Comment by Derek-Jones** [comment]
Same incorrect behavior on Firefox 115.0.2 running
Distributor ID:	Linuxmint
Description:	Linux Mint 21.1
Release:	21.1
Codename:	vera

**Comment by gvwilson** [comment]
combined with #157
