### ISSUE TITLE
/func: diagram renders incorrectly

### ISSUE THREAD

**Issue by gvwilson** [gvwilson/sdxpy#160]
![Screenshot 2023-07-12 at 23-41-31 Software Design by Example Functions and Closures](https://github.com/gvwilson/sdxpy/assets/911566/1a109713-8c2e-42ec-a143-d50768c6cb9b)

Submitted by @Derek-Jones

**Comment by gvwilson** [comment]
Firefox version 108 on Ubuntu

**Comment by gvwilson** [comment]
Unable to reproduce on Firefox 117 and Ubuntu Focal 20.04.6.

**Comment by Derek-Jones** [comment]
Same incorrect behavior on Firefox 115.0.2 running
Distributor ID:	Linuxmint
Description:	Linux Mint 21.1
Release:	21.1
Codename:	vera

**Comment by gvwilson** [comment]
combined with #157
