### ISSUE TITLE
/glob - Test-Driven Development (2023-07-13) Failed test points to wrong test

### ISSUE THREAD

**Issue by scmbradley** [gvwilson/sdxpy#173]
At the end of this section, `test_either_followed_by_literal_no_match` fails simply because there's no `.match("ax")` method call in the test. So you get returned an `Either` object, which is not falsy. 

What should happen is `test_either_followed_by_literal_match` should fail once you add the `match("ac")` method call. So the text is broadly right that there's a bug here, but there's also a bug in the tests which means you're pointing the finger at the wrong test.

**Comment by gvwilson** [comment]
closed by b4db62a2 - thank you
