### ISSUE TITLE
/test: clarify aliasing in slides

### ISSUE THREAD

**Issue by hectorcorrea** [gvwilson/sdxpy#190]
The code in [the tester slides](https://github.com/gvwilson/thirdbit/blob/main/sdxpy/tester/slides/index.html#L78):

```
-   We can assign that value to another variable

```python
alias = example
alias()
```

makes sense to me today, but years ago, the first time that I was introduced to the idea that a function can be assigned to a variable, it was a confusing idea. As a beginner it was hard to conceptualize that `alias = example` was assigning `alias` with a pointer to the `example` function and NOT the value returned by the `example()` function. 

I think the naming the left side `alias` as you do certainly helps the reader, but I would suggest adding a note so that the reader is aware that this is not a call to the `example()` function.

**Comment by gvwilson** [comment]
closed in c537f121
