### ISSUE TITLE
/oop - wrong output shown

### ISSUE THREAD

**Issue by ghost** [gvwilson/sdxpy#196]
Maybe I'm just dense, lol, but it took me quite a while to find a link to this repo. So...

maybe add more links to here in various places, or just nice and clear at the top of the Contributing page so that people don't have to go searching for the link to the repo.

Now with that said, it's either me, or, I think the very first code example in Chapter 2, I think the output is wrong.

I'm getting "12.00 9.00" and the example says 12.00 and 12.00.

Thank you for this awesome book!

**Comment by gvwilson** [comment]
- Link to repo added to page header in af79df5e
- Content bug will be addressed separately in the next round of revisions

**Comment by beeburrt** [comment]
Wow, that was quick :)

If I were to do a pull request, do want a similar title as you did here?

**Comment by gvwilson** [comment]
That would be great - thank you.
