### ISSUE TITLE
Missing sections in CONTRIBUTING.md on website frontend

### ISSUE THREAD

**Issue by gitgithan** [gvwilson/sdxpy#210]
![image](https://github.com/gvwilson/sdxpy/assets/29853829/ce0ce1c6-ca26-4e09-9eba-d2de71ce7e1c)

https://third-bit.com/sdxpy/contrib/ ends at **Section F.3: Making Decisions** so beginning from Formatting section onwards in CONTRIBUTING.md, it is not shown. 
Wasn't easy figuring out what all the `# [use]` mean't since ark documentation is not popular in search engines and am still struggling even with their official docs, though i do get that it affects what code sections gets shown on website

**Comment by gvwilson** [comment]
Thanks for the issue - I'm not sure what to change to close it:
1. `./CONTRIBUTING.md` is meant to be the full guide for contributors, including a detailed description of formatting using Markdown with Ark/Ibis extensions.
2. <https://third-bit.com/sdxpy/contrib/> is the text that will go into the published book; it is shorter on purpose.
3. I agree that there isn't as much documentation for Ark as there is for other static site generators, but I hope that potential contributors will be able to copy-and-paste, imitate, or ask me for help - I'd like to write a full Ark tutorial, but it's way down my to-do list.

**Comment by gvwilson** [comment]
Thank you - I'll add a note to `src/contrib/index.md` pointing people at `./CONTRIBUTING.md` for the full description of our Markdown extensions, and then close this issue. (You're right, it isn't clear where to look for what...)
