### ISSUE TITLE
/func review

### ISSUE THREAD

**Issue by gvwilson** [gvwilson/sdxpy#220]
Please review Chapter 8 https://third-bit.com/sdxpy/func/

cc @peter0083

**Comment by peter0083** [comment]
will do!

**Comment by peter0083** [comment]
```
The answer for the [%i "interpreter" %] of [%x interp %] is pretty easily"
but the answer for the little language it interprets is "not at all"
```
Extra quotation mark at the end of line 24?

https://github.com/gvwilson/sdxpy/blob/c48be48382c460d9f248bd3db4f073f7de08bca2/src/func/index.md?plain=1#L24

**Comment by peter0083** [comment]
```
It has a name,
a (possibly empty) list of parameters,
and a body,
which in this case is a single [%i "statement" %].
```
missing a comma after "which in this case"?

suggestion:
```
It has a name,
a (possibly empty) list of parameters,
and a body,
which in this case, is a single [%i "statement" %].
```
https://github.com/gvwilson/sdxpy/blob/c48be48382c460d9f248bd3db4f073f7de08bca2/src/func/index.md?plain=1#L45

**Comment by peter0083** [comment]
`https://third-bit.com/sdxpy/func/func.tll`  link on `https://third-bit.com/sdxpy/func/` page leads to a 404.

**Comment by peter0083** [comment]
output from 
https://github.com/gvwilson/sdxpy/blob/c48be48382c460d9f248bd3db4f073f7de08bca2/src/func/oop.py#L15

and output shown in 
https://github.com/gvwilson/sdxpy/blob/c48be48382c460d9f248bd3db4f073f7de08bca2/src/func/oop.out#L2

are inconsistent. Not sure which you prefer.

**Comment by peter0083** [comment]
https://github.com/gvwilson/sdxpy/blob/c48be48382c460d9f248bd3db4f073f7de08bca2/src/func/index.md?plain=1#L267

should it be `(i.e., treats everything after the parameter list as an implicit "seq").`?
