### ISSUE TITLE
/viewer review

### ISSUE THREAD

**Issue by gvwilson** [gvwilson/sdxpy#221]
Please review Chapter 23 https://third-bit.com/sdxpy/viewer/

cc @elevenyao11

**Comment by elevenyao11** [comment]
https://github.com/gvwilson/sdxpy/blob/971db394e19a0f8f294e06b72844a12ec2e7fa58/src/viewer/viewport.py#L25
should be self._buf.ncol(self._pos[ROW]) - 1,

**Comment by elevenyao11** [comment]
The file coord_const.py in the github folder https://github.com/gvwilson/sdxpy/blob/main/src/viewer/ should be named as cursor_const.py to be aligned with other codes.
