### ISSUE TITLE
/db review

### ISSUE THREAD

**Issue by gvwilson** [gvwilson/sdxpy#223]
cc @metawake

**Comment by metawake** [comment]
@gvwilson first issue in "Database" chapter is wrong import. The class is first named "class BasicRec" but is referred by test_db_original.py as "BasicExperiment".
That can be fixed at import time by "from record_original import BasicRec as BasicExperiment".

**Comment by metawake** [comment]
Some small ongoing questions about the db chapter:
https://github.com/gvwilson/sdxpy/issues/239
