### ISSUE TITLE
Typo in chart in oop/inherit_class.svg

### ISSUE THREAD

**Issue by FlorianGD** [gvwilson/sdxpy#245]
Hello,
The `oop/inherit_class.svg` chart mentions a  `shout` entry to the `Shape` dictionary, whereas the text above talks about a `density` entry.
Sorry, I am on my phone so I cannot try and fix it directly. This is minor, but could be confusing.
Thanks for the nice project that I am discovering!

**Comment by gvwilson** [comment]
thank you - pushing the fix now...
