### ISSUE TITLE
Figure 3.1 is incorrect

### ISSUE THREAD

**Issue by Hofer-Julian** [gvwilson/sdxpy#261]
The following snippet is described by Figure 3.1

```python
def find_duplicates(filenames):
    matches = []
    for i_left in range(len(filenames)):
        left = filenames[i_left]
        for i_right in range(i_left):
            right = filenames[i_right]
            if same_bytes(left, right):
                matches.append((left, right))
    return matches
```

![grafik](https://github.com/gvwilson/sdxpy/assets/30049909/52df1b59-4268-4485-ad5e-604f9ec11001)

However, as far as I can tell, the following fields are looped through:

![Neues Dokument - Selection](https://github.com/gvwilson/sdxpy/assets/30049909/9bc6c928-0232-4dd8-8b3e-e2d294f8c257)

**Comment by gvwilson** [comment]
thank you - I'll push a fix on the weekend.
