### ISSUE TITLE
 mini Jupyter Notebook like

### ISSUE THREAD

**Issue by hamzzy** [gvwilson/sdxpy#264]
I'm eager to contribute to the creation of a mini Jupyter notebook. This would offer learners a valuable opportunity to grasp the fundamental architecture and gain insights into how Jupyter functions beneath the surface.

**Comment by gvwilson** [comment]
thank you, but after some thought I think it's out of scope for this book - if you'd like to do an entire book on that (perhaps building on http://browser.engineering/ ?) I think that would be great.
