### ISSUE TITLE
Introduction - more about personas?

### ISSUE THREAD

**Issue by vcheplygina** [gvwilson/sdxpy#54]
A bit outside of the scope perhaps :) But as somebody who identifies to some extent with all the three personas at different points in life I am really curious to know more, and how this relates to the prerequisites. 

* Why did Aïsha switch from Wordpress to Django, and where did she learn Python, Git, trees & recursion? 
* Does Rupinder use Git and style checkers because the course the teacher told everyone to, or is it a practice he adopted elsewhere?
* What did Yim do before their teaching position, and what does the rest of their students' curriculum look like? 

Can there be more than three personas, or is that a convention?

**Comment by gvwilson** [comment]
More details added
