### ISSUE TITLE
Introduction - overview / example projects?

### ISSUE THREAD

**Issue by vcheplygina** [gvwilson/sdxpy#55]
I would love to see one or more projects (from real life, or perhaps that the personas are working on), and how each part/chapter looks like for that project, maybe a diagram which parts "talk together",  perhaps motivating the ordering of the chapters

**Comment by gvwilson** [comment]
I thought about having the examples build on each other (e.g., to create an entire IDE) but that introduces maintenance headaches and constraints teaching. I've added a section on teaching notes in 9cb1584 that I hope explains the reasoning.
