### ISSUE TITLE
/templating: too large empty space in lstlisting

### ISSUE THREAD

**Issue by juananpe** [gvwilson/sdxpy#79]
I've spent some time trying to figure out how to solve this strange bug, to no avail:

<img width="760" alt="image" src="https://user-images.githubusercontent.com/1078305/209120628-1920c299-2301-4bc8-a48f-5cc6051fa511.png">

It can be fixed wrapping  a `minipage` inside the `lstlisting` tag (I tried applying [that fix](https://tex.stackexchange.com/a/73305) directly in the TeX file and it worked), but I think that it should be a simpler way.

**Comment by gvwilson** [comment]
That could be an issue with the CSS - I usually leave those kinds of rendering issues until the very end when the content has settled down in the hope that the problematic example will be discarded during revision and I won't have to figure it out :-)
