### ISSUE TITLE
/lint: notation unclear / not explained

### ISSUE THREAD

**Issue by ceedee666** [gvwilson/sdxpy#96]
The figure (https://github.com/gvwilson/sdxpy/blob/ce377531284949ac11fdcb7bf0bbf60b470959af/en/src/linter/index.md?plain=1#L49) shows a representation of the AST of the Python program from the previous code snippet (https://github.com/gvwilson/sdxpy/blob/ce377531284949ac11fdcb7bf0bbf60b470959af/en/src/linter/index.md?plain=1#L42).

In my opinion the image has as view short comings:

1. The notation is never explained. What do boxes represent? What do named arrows represent?
2. Why are some part of the AST shown in the image while others are omitted (e.g. name attribute of the function definition)?
3. The `return` below `FunctionDef`should be `body`

Regarding the notation I would suggest to show all attribs of the AST. Maybe similar to a class notation in UML. Or do get rid of the named arrows and just use nodes.

**Comment by gvwilson** [comment]
closed in c537f121
