### ISSUE TITLE
/lint: invocation missing

### ISSUE THREAD

**Issue by ceedee666** [gvwilson/sdxpy#97]
In the code snippet for finding duplicate keys (cf. https://github.com/gvwilson/sdxpy/blob/ce377531284949ac11fdcb7bf0bbf60b470959af/en/src/linter/index.md?plain=1#L165) the Python code to invoke the class is missing (i.e. code starting at https://github.com/gvwilson/sdxpy/blob/ce377531284949ac11fdcb7bf0bbf60b470959af/docs/linter/find_duplicate_keys.py#L25). I would suggest adding it to be more clear.

**Comment by gvwilson** [comment]
closed in c537f121
